ci:
  autoupdate_schedule: 'quarterly'
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-docstring-first
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v2.5.1'
    hooks:
      - id: prettier
        types: [ts]

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: 'v8.6.0'
    hooks:
    - id: eslint
      files: \.ts$  # *.ts
      types: [file]
      additional_dependencies:
        - eslint
        - prettier
        - typescript
        - '@typescript-eslint/eslint-plugin'
        - '@typescript-eslint/parser'
        - 'eslint-config-prettier'
        - 'eslint-plugin-prettier'
